name = "GenomicBreeding"
uuid = "10ae3e88-9fae-48f7-b74d-53e776fee7da"
authors = ["jeffersonparil@gmail.com"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GenomicBreedingCore = "50d95318-1838-4cfa-a614-3543b4bb0509"
GenomicBreedingIO = "f6f5bf5f-7369-4de1-9a2f-51e3ce5e0754"
GenomicBreedingModels = "a21a2f6e-06ad-4936-9990-fa46b058b9d4"
GenomicBreedingPlots = "2d71191b-ccd5-4418-88d2-30d4b74b1774"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[sources]
GenomicBreedingCore = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingCore.jl"}
GenomicBreedingIO = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingIO.jl"}
GenomicBreedingModels = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingModels.jl"}
GenomicBreedingPlots = {rev = "main", url = "https://github.com/GenomicBreeding/GenomicBreedingPlots.jl"}

[compat]
DataFrames = "1.7.0"
Dates = "1.11.0"
Documenter = "1.8.0"
GenomicBreedingCore = "0.1.0"
GenomicBreedingIO = "0.1.0"
GenomicBreedingModels = "0.1.0"
GenomicBreedingPlots = "0.1.0"
ProgressMeter = "1.10.2"
StatsBase = "0.34.4"
UnicodePlots = "3.7.2"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
